---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yelb-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: db
  name: yelb-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelb-db
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yelb-db
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: db
    spec:
      containers:
      - name: yelb-db
        image: {{ .Values.image_yelb_db }}:{{ .Values.imageTag_yelb_db }}
        ports:
        - containerPort: 5432
      restartPolicy: Always

