---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yelb-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: db
  name: yelb-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: yelb-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: db
  type: ClusterIP
