stages:
- kubectl

Kubectl:
  stage: kubectl
  image:
    name: bitnami/kubectl:1.18.2
    entrypoint: [""]
  variables:
    KUBECONFIG: /tmp/.kubeconfig
  script:
  - echo "$K8S_CONFIG" | base64 -d > $KUBECONFIG
  - kubectl get nodes