---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: sql-proxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: sql-proxy
  name: yelb-db
spec:
  selector:
    app: sql-proxy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: sql-proxy
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
