---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: redis
  name: redis-server
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: app
  type: ClusterIP
