---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yelb-ui
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: {{.Release.Name}}
    heritage: {{.Release.Service}}
    component: ui
  name: yelb-ui
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: yelb-ui
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: {{.Release.Name}}
    heritage: {{.Release.Service}}
    component: ui
  type: ClusterIP
