---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yelb-appserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: appserver
  name: yelb-appserver
spec:
  ports:
    - port: 4567
      targetPort: 4567
  selector:
    app: yelb-appserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: appserver
  type: ClusterIP
